openllb/hlb

codegen/codegen.go

in codegen.go you have:
```
for _, iopt := range iopts {
opt := iopt.(llb.MountOption)
mountOpts = append(mountOpts, opt)
}
```
but llb.Readonly is type `func(*mount)`, so it needs to be cast explicitly.  Otherwise we get this panic:
```
interface conversion: interface {} is func(*llb.mount), not llb.MountOption
```

fix casting for llb.Readonly to force llb.Mountoption to prevent panic

---

checker/checker.go
module/resolve.go
module/tree.go
module/vendor.go
parser/cst.go
parser/unparse.go
parser/walk.go

Necessary to highlight the keywords `import`, `export`, `from`, and the import path for local imports.

Expose more granular CST nodes for import/export

---

go.hlb
module/resolve.go
module/vendor.go
parser/cst.go
parser/unparse.go
source.hlb

- Did some touchups in packages `module` and `parser`.
- Broke up `source.hlb` into `go.hlb` using  relative imports

Touchup module and parser packages, and use imports to break up source.hlb

---

cmd/hlb/command/app.go
cmd/hlb/command/version.go
go.hlb
source.hlb
version.go

Fixes issues #10 
This uses the git tag + distance to version the binary.  It adds an `hlb version` command which will print something like:
```
$ build/hlb-darwin-amd64 version
0.1-43-gf1453b1
```
The `0.1` is from the version tag, the `43` is the distances in commits since the version tag, and the `gf1453b1` is a `g` plus the git sha for HEAD.  The version string is derived from `git describe --tags --always`.  The version will have an extra `.dirty` on the end if it was compiled from modified sources.
I am not happy with the changes necessary to the `go.hlb` file, but I could not figure out anything better.   At least it seems to work.

add version command and infer version from git tag

---

.github/workflows/test.yml
hlb.go

Fixes issue #32
This is what we will see now:
```
$ ./hlb --addr docker-container://buildkitd run --target bogus ./source.hlb
target "bogus" is not defined in ./source.hlb
```
```
$ cat ./source.hlb | ./hlb --addr docker-container://buildkitd run --target bogus
target "bogus" is not defined in /dev/stdin
```

[#32] return error when requested target is not defined

---

codegen/codegen.go

fixes #40 
Input:
```
fs issue40() {
image "alpine:latest"
run "pwd" with myopt
}
option::run myopt() {
dir "/etc"
}
```
Output:
```
$ ./hlb run -t issue40 --log-output plain ./tests/bug.hlb
#1 compiling ./tests/bug.hlb
#1 DONE 0.0s
#2 docker-image://docker.io/library/alpine:latest
#2 resolve docker.io/library/alpine:latest
#2 resolve docker.io/library/alpine:latest 0.7s done
#2 DONE 0.7s
#2 docker-image://docker.io/library/alpine:latest
#2 CACHED
#3 pwd
#3 0.101 /etc
#3 DONE 0.1s
```

[#40] fix usage of `with myoption`

---

cmd/hlb/command/run.go
codegen/codegen.go
solver/solve.go

fixes #43 
Example input:
```
$ cat ./tests/bug.hlb
fs secretTest() {
image "busybox:latest"
dir "/dir"
run "ls" with option {
secret "./tests/bug.hlb" "/dir/bug.hlb"
}
}
```
```
$ ./hlb run -t secretTest --log-output plain ./tests/bug.hlb
#1 compiling ./tests/bug.hlb
#1 DONE 0.0s
#2 docker-image://docker.io/library/busybox:latest
#2 resolve docker.io/library/busybox:latest
#2 resolve docker.io/library/busybox:latest 1.1s done
#2 sha256:b26cd013274a657b86e706210ddd5cc1f82f50155791199d29b9e86e935ce135 1.86kB / 1.86kB done
#2 sha256:afe605d272837ce1732f390966166c2afff5391208ddd57de10942748694049d 527B / 527B done
#2 sha256:0669b0daf1fba90642d105f3bc2c94365c5282155a33cc65ac946347a90d90d1 0B / 760.80kB 0.1s
#2 sha256:83aa35aa1c79e4b6957e018da6e322bfca92bf3b4696a211b42502543c242d6f 1.49kB / …
```

[#43] plumb secret imports through to llb client

---

codegen/codegen.go
codegen/decl.go
compile_test.go

fixes #52 
I ended up needing this fixed to work though some testing on #51, so submitting this first.  
Basically I ended up caching the llb.State at the time of the alias definition, then looking that up late rather than attempting to regenerate the llb.State every time the alias is used (causing the infinite recursion when used within the same fs). 
I also removed the aliasCallback, it seemed unnecessary except for the one case where we were trying to lookup to alias results, which I solved by moving the cache into the codegen struct.

[#52] fix stack overflow when using alias within same fs

---

checker/checker.go
checker/errors.go
codegen/codegen.go
compile_test.go

fixes #51 
This allows multiple sources to be used within a single fs.  fs "methods" will continue to operate on the previous state in the stack/chain.

[#51] remove methods and single-source requirements from fs blocks

---

.golangci.yml
parser/cst.go

This pr migrates the particle struct tags to use the `parser:"..."` form. Otherwise, editors and linters produce warnings about the syntax.

use `parser:"..."` struct tags so editors/linters stop complaining

---

codegen/codegen.go
codegen/decl.go
codegen/expr.go
hlb.go

- Codegen was dropping most errors! D'oh!
- Expressions are arguments to functions. Since arguments cannot have arguments of their own, this was just bad logic plumbing arguments down to function exprs and option exprs.
- We don't need to do target overrides when there isn't any cli output flags.

Ensure exprs don't ever have args, fix codegen dropping errs

---

codegen/codegen.go

Because of confusingly named variables the wrong path was passed to the solver to map the id to the path. I renamed them to clear the confusion and fix secrets.

Fix secret to provide correct local path

---

checker/errors.go
cmd/hlb/command/run.go
codegen/codegen.go
codegen/debug.go
codegen/decl.go
codegen/errors.go
codegen/expr.go
compile_test.go
go.mod
hlb.go
solver/progress.go

Fixes #66 
- Depending on if you're in debug mode or not, we used to split off the flows to deal with a nil `*solver.Progress`. Instead, we move it to an interface and build a `debugProgress` concrete implementation to hide complexity from caller side.
- The progress write in `hlb.Compile` hides the error from codegen because the error is sent to the vertex sent via the solve status channel. Due to how it's implemented in the error contents are not shown in the progress UI but shown in progress plain. We ported it to `func write` that writes to the vertex logs, and also the stack trace if `errors.WithStack` is used.
- There used to be many panics in `codegen` because it should only deal with correct CSTs. However, bugs do happen and we want to make it easy to diagnose the issue. I …

Build one flow for codegen to solve using solver.Progress interface, plumb stacktrace to progress UI

---

checker/checker.go
codegen/codegen.go
codegen/decl.go
codegen/expr.go

Fixes #67 
This is a `codegen` error not a `checker` one so we don't have test framework for this yet unfortunately.
The problem was that I was incorrectly passing in the option subtype when parameterizing the function. It should be based on the function signature's field's type, but for some reason I decided to plumb the `op string` from somewhere. You can see it being `""` most of time, indicating something smelly to begin with.

Parameterize functions using correct option subtype

---

codegen/codegen.go
codegen/decl.go
codegen/expr.go

Fixes #71 
- StateOption needs to be able to return `error` so we defined our own. Also needed for: #63
- Alias needs to short circuit and exit early using `ErrAliasReached`, the current `break` isn't enough to avoid recursion
```sh
❯ hlb run --log-output plain foo.hlb
#1 compiling [default]
#1 DONE 0.0s
#2 docker-image://docker.io/library/busybox:latest
#2 resolve docker.io/library/busybox:latest
#2 resolve docker.io/library/busybox:latest 0.4s done
#2 DONE 0.4s
#3 /bin/sh -c touch foo
#3 CACHED
#4 /bin/sh -c ls -la
#4 0.280 total 8
#4 0.280 drwxr-xr-x    1 root     root          4096 Apr 10 00:15 .
#4 0.280 drwxr-xr-x    1 root     root          4096 Apr 10 00:15 ..
#4 0.280 -rw-r--r--    1 root     root             0 Apr 10 00:14 foo
#4 DONE 0.4s
```

Allow mounts to be reused in the same fs

---

codegen/codegen.go
codegen/debug.go
module/resolve.go
solver/request.go
solver/solve.go

Fixes #61 
- `(llb.State).Marshal` isn't concurrent safe. We wanted to move `solver.Request` to use `*llb.Definition` instead of `llb.State` because marshalling with constraints should be part of `codegen` at some point.
- Removes `exec` from debugging, we want to use the `Exec` RPC from BuildKit in the future, it's starting to become a maintenance burden when making bigger changes. https://github.com/moby/buildkit/issues/749

Avoid marshalling the same llb.State in parallel, remove debug exec

---

checker/errors.go
cmd/hlb/command/run.go
codegen/codegen.go
codegen/decl.go
codegen/output.go
compile_test.go
hlb.go

- Generating dynamic CST is bad because it's hard to integrate with error reporting and debugging.
- Previously you weren't able to define multiple outputs per target on the CLI, now you can do duplicates like `hlb run -t foo,dockerPush=hinshun/foo:latest,dockerPush=hinshun/foo:stable`
- Refactored duplicate code

Refactor outputs and CLI outputs

---

codegen/codegen.go
codegen/codegen_test.go
codegen/output.go
solver/request.go
solver/solve.go

- Simplified how `llb.Local` id is calculated. The terminal op of the graph `def.Def[len(def.Def)-1]` is an empty vertex with an input to the last vertex's digest. Since that vertex also has its digests of its inputs and so on, the digest of the terminal op is a merkle hash for the graph.
- Change `solver/request` to be more testable
- Add `(solver.Request).Tree` to debug solve trees and compare results with expected value
```sh
❯ go test -v ./codegen
=== RUN   TestCodeGen
=== RUN   TestCodeGen/image
=== PAUSE TestCodeGen/image
=== RUN   TestCodeGen/call_function
=== PAUSE TestCodeGen/call_function
=== RUN   TestCodeGen/local
=== PAUSE TestCodeGen/local
=== CONT  TestCodeGen/image
=== CONT  TestCodeGen/local
=== CONT  TestCodeGen/call_function
--- PASS: TestCodeGen (0.00s)
--- PASS: …
```

Add codegen test framework

---

codegen/codegen.go
solver/request.go

Current output:
```
hlb run --tree ./source.hlb
[+] Building 1.6s (1/1) FINISHED
=> compiling [default]                                                                                                                                                                                        1.6s
.
└── parallel
└── parallel
├── single
│   └── [exec]  meta:<args:"/bin/sh" args:"-c" args:"v=$(git describe --match 'v[0-9]*' --tags --dirty='.dirty' --always | sed 's/^v//') && LDFLAGS=\"-X github.com/openllb/hlb.Version=$v\" /cross/build \"github.com/openllb/hlb/cmd/hlb\"" env:"PATH=/osxcross/target/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" env:"GOLANG_VERSION=1.13.10" env:"OSX_CROSS_PATH=/osxcross" env:"GOPATH=/root/go" env:"GO111MODULE=on" …
```

update tree output for exec to make more readable

---

builtin/builtin.go
checker/checker.go
codegen/codegen.go
codegen/codegen_test.go
codegen/decl.go
codegen/expr.go
language/builtin.hlb
parser/cst.go

Fixes #47 
- Group statements are sequential, there is a builtin `parallel` that accepts variadic groups to execute them in parallel
- `fs` can be coerced to `group` but `group` cannot be coerced to `fs`
```hlb
group foo() {
createFoo "hello"
appendFoo " world"
}
fs createFoo(string msg) {
scratch
mkfile "foo" 0o644 msg
download "."
}
fs appendFoo(string msg) {
scratch
copy fs { busyboxAppendFoo msg; } "/foo" "/"
download "."
}
fs busyboxAppendFoo(string msg) {
image "busybox"
copy fs {
local "." with option { includePatterns "foo"; }
} "foo" "/foo"
run string {
format "echo \"%s\" >> /foo" msg
}
}
```
```sh
$ hlb run -t foo source.hlb
[+] Building 1.2s (8/8) FINISHED
=> compiling [foo] …
```

Implement sequential and parallel groups

---

builtin/builtin.go
codegen/codegen.go
codegen/codegen_test.go
language/builtin.hlb

See test for example.
I chose `localEnv` to distinguish it from the `env` instruction for `fs`. Perhaps `getEnv` is better? WDYT?

Add localEnv string builtin

---

builtin/builtin.go
language/builtin.hlb

They weren't matching the `codegen` for `allowWildcard`.

Fix wildcard builtins

---

checker/checker.go
checker/checker_test.go
cmd/hlb/command/run.go
codegen/chain.go
codegen/codegen.go
codegen/codegen_test.go
codegen/decl.go
codegen/expr.go
go.hlb
parser/cst.go
parser/unparse.go
parser/walk.go
solver/request.go

- Refactored `EmitChainXYZ` functions to `codegen/chain.go`
- Refactored `EmitChainXYZ` to depend on `expr *parser.Expr, args []*parser.Expr` instead of `call *parser.CallStmt` (So that `EmitXYZExpr` functions can call `EmitChainXYZ`. Reducing code duplication)
- Removed `call *parser.CallStmt` from `EmitStringExpr`, turns out it was unused.
- Made chain functions consistent (before: `StateOption`, `GroupChain`, `func(string) (string, error)`) (after: `FilesystemChain`, `GroupChain`, `StringChain`)
Now you can call builtin functions that have zero args directly:
```hlb
fs default() {
image "alpine"
run "touch /out/foo" with option {
mount scratch "/out" as fooOut
}
}
```

Refactor codegen to allow calling functions without arguments as an expression

---

codegen/chain.go
codegen/codegen.go
codegen/codegen_test.go
go.mod
go.sum

- Paths are resolved to the module's filepath. So you can import modules and execute them without all the relative paths incorrect. See: https://github.com/hinshun/earthly/commit/d4ca01bda635eb24b3360ece9c9555e0707b9fdc
- Also supports home dir resolving via `go-homedir` (Fixes #2)
```hlb
fs homeConfiguration() {
local "~/.myconfig"
}
```
- Supply `llb.SharedKeyHint` so that different relative strings that are pointing to the same underlying directory are deduplicated when transferring to BuildKit.
```hlb
fs default() {
local "."
}
```
```hlb
fs default() {
local "../"
}
```

Resolve paths relative to the module's filepath

---

codegen/chain.go

HEREDOCs makes the progress UI go pretty crazy. This preserves the newline in execution, but changes the vertex name so that its a one-liner for the display.

Remove new lines in vertex name for heredocs

---

cmd/hlb/command/run.go
codegen/chain.go

- Fixes the replace that changed `source` to `fcrce` from a previous PR.
- Returns when progress returned and error and `solveReq` is nil.

Fix frontend builtin and exiting when progress returns error

---

codegen/codegen.go

```hlb
fs a() {
image string {
template "{{ invalid }}"
}
}
group b() {
image string {
template "{{ invalid }}"
}
}
```
```sh
$ hlb run -t a foo.hlb
[+] Building 0.0s (1/1) FINISHED
=> ERROR compiling [a]                                                                                                                                               0.0s
------
> compiling [a]:
#1 0.000 Caused by: template: foo.hlb:3:3:1: function "invalid" not defined
------
$ hlb run -t b foo.hlb
[+] Building 0.0s (1/1) FINISHED
=> ERROR compiling [b]                                                                                                                                               0.0s
------
> compiling [b]:
#1 0.000 Caused by: template: foo.hlb:9:3:1: function "invalid" not defined
------
```

Fix group blocks from dropping errors

---

checker/checker.go
checker/checker_test.go
codegen/chain.go
codegen/codegen_test.go
codegen/decl.go
codegen/expr.go
parser/cst.go
solver/request.go

- Coerce fs func lit into group func lit
- Add `treeprint` branches for solve options so that they are testable
- Add codegen test
```
group default() {
parallel group {
image "alpine"
} fs {
scratch
mkfile "foo" 0o644 "hello world"
download "."
}
}
```

Coerce fs func lit into group func lit

---

checker/checker.go
checker/checker_test.go
checker/errors.go

- Previously cannot use selector as an argument:
```
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/openllb/hlb/checker.(*checker).checkCallArgs(0xc00036c4b0, 0xc0002442e0, 0xc0000d3dc0, 0x0, 0x0, 0x0, 0x0, 0x1)
/home/edgarl/go/src/github.com/openllb/hlb/checker/checker.go:435 +0x2aa
```

Allow selectors to be used as arguments

---

codegen/codegen.go
codegen/codegen_test.go
solver/request.go
solver/solve.go

- Currently, you are not allowed to change `network "host"` or `security "insecure"`. Ported over the `AllowedEntitlements` from `buildctl`.
- However, this still requires the `buildkitd` side to also allow these entitlements, so it won't work on cloud build.
```
#1 DONE 0.0s
ERROR   failed to solve: rpc error: code = Unknown desc = failed to load LLB: security.insecure is not allowed
```

Set allowed entitlements on solve opt to allow changing network and security mode

---

builtin/builtin.go
codegen/chain.go
language/builtin.hlb

I want to have a `hlb run` that automatically cross compiles for my current platform (darwin) but I need to pass in my local OS and Arch to the build graph.
Also I think there are some use-cases where `cwd` is relevent for building/exporting files back to the local workspace. `gdb` for example will only read source files if the strings embedded in the binary headers match the local system paths, so debugging a binary built in `/src` will not be easy if the sources are actually in `$HOME/project/src`.  With `localCwd` it will allow for patterns like:
```
fs build() {
run "make" with option {
dir localCwd
mount fs { local "."; } localCwd
}
}
```

add localOs, localArch, and localCwd builtins

---

builtin/builtin.go
codegen/chain.go
codegen/codegen.go
codegen/codegen_test.go
language/builtin.hlb

Also automatically add mount directories for secrets/mounts on top of `readonly` fs
I will add some codegen tests, just wanted to get your thoughts on this.  It seems to work, greatly simplified the mkdir/mkfile copy/paste I had all over so that I could get caching on builds from local inputs.

allow for directory in arguments to `secret`

---

checker/checker.go
checker/checker_test.go
codegen/chain.go
codegen/codegen.go
codegen/debug.go
parser/cst.go

- Previously didn't allow `run "echo foo" with myimport.foo`
- We need some way of running codegen tests with imports, but going to take more work since we need a sandboxed buildkitd or some small mock framework for imports.

Allow option funcs to be used from imported

---

codegen/chain.go
codegen/codegen.go
codegen/decl.go
codegen/errors.go
codegen/expr.go

- Codegen was originally designed to assume that the CST is correct but inevitably bugs are present so we need a good trace that includes source mapping to the HLB file, line and column.
- I'm making a few PRs to refactor different parts of the codegen to produce better errors.

Output error stack instead of panicking on bad cast

---

checker/checker.go
checker/checker_test.go

- Panics because `fun.Scope` is nil when duplicate decl is encountered
- We had two choices here: 1) Exit early when encountering duplicate declarations, but that means other errors won't show up, 2) Don't override scope with duplicate but continue constructing scope, etc. I chose (2) so that we show other errors too.
- `validateError` was hiding other errors because it only checked the first element, I think checking `expected.Error()` vs `actual.Error()` was sufficient because `ErrSemantic` with one element has the same output.

Construct function scope, and so forth for duplicate declarations

---

codegen/chain.go
codegen/codegen.go
codegen/debug.go
codegen/errors.go
codegen/expr.go

- Instead of panicking with nil dereference, show the source mapping and stack for the error.

Return error on bad lookups during codegen

---

codegen/chain.go
codegen/codegen_test.go
docs/reference.md
language/builtin.hlb

- Currently, if you specify a single file like `local "manifest.json"` then it fails with:
```sh
ERROR   failed to solve: rpc error: code = Unknown desc = error from sender: manifest.json is not a directory
```
- Instead `local "manifest.json"` should be the equivalent of: `local "." with option { includePatterns "manifest.json"; }`, with the caveat that if the `path` is for a file then include and exclude patterns are ignored.

Allow local to specify a single file instead of a directory

---

module/resolve.go

- Currently I can't import a frontend like so:
```hlb
import hlbgen from fs {
frontend "hinshun/hlbgen"
}
```
- The remote resolver should pass the client and multiwriter it already has.

Fix remote imports that have frontend codegen

---

codegen/codegen.go
docs/reference.md
language/builtin.hlb

The implementation is a bit of a hack.  There does not seem to be a way via llb to make an exec call force a cache-miss other than `llb.IgnoreCache`, but that will also prevent any mounts from also using cache. 
So this PR adds a random env var so that the vertex will always hash to a new digest while still allowing mount cache to be used.

add `always` builtin for `run` to force command to always run (but allow cached mounts)

---

codegen/codegen.go
codegen/output.go

- `downloadTarball`, `downloadOCITarball`, and `downloadDockerTarball` did not successfully download files.
- Errors from this code path were also being dropped because `err` was returned (which was `nil`) instead of `cerr`.

Fix download file outputs and hidden error

---

codegen/codegen.go

fixes #134
You were right, the `imagemetaresolver.WithDefault` was resolving for my client platform (Darwin) while it needs to be resolving for the deployment platform.  We will likely need to make all these hard-coded linux/amd64 arguments configurable for when we have non-linux remote cloudbuild systems, but for now it seems okay.

[#134] resolve for remote platform, not client platform

---

checker/checker_test.go
parse.go
parser/parse.go
parser/unparse.go
unparse_test.go

Fixes #135 
- Wraps the `io.Reader` with a `NewlinedReader` that appends a newline before the natural EOF.
- Removes complexity dealing with zero-newline inputs. I didn't see much value in unparsing one-liners to retain one-liners.

Fix parsing error with inputs not ending with newline

---

checker/checker.go
checker/checker_test.go
checker/errors.go
parser/cst.go

Fixes #144
- Before, the bad regex consumed too much `0644 \"content\"`, we should delimit bad tokens by whitespace
New error:
```sh
❯ hlb run test.hlb
test.hlb:2:22: unable to parse "0644"
```

Break up bad lexemes by spaces so that we can return the correct syntax error

---

report/syntax.go

Fixes #145
Fixes #146
```sh
--> foo.hlb:3:40: syntax error
|
3 |                 format "%s/%s" "alpine", "git"
|                                        ^
|                                        unexpected token "," (expected ";" | <newline> | <comment>)
```
```sh
--> foo.hlb:2:25: syntax error
|
2 |         image "busybox" {
|                         ^
|                         unexpected token "{" (expected ";" | <newline> | <comment>)
```
```sh
--> foo.hlb:2:38: syntax error
|
2 |         image "busybox" with hoption {
|                                      ^
|                                      unexpected token "{" (expected ";" | <newline> | <comment>)
```
```sh
--> foo.hlb:2:18: syntax error
|
2 | 	image "busybox" with option resolve
| 	                ^^^^
| …
```

Catch default errors to avoid syntax 0:0 errors

---

codegen/chain.go
codegen/codegen.go

Specifically this segfaults because the gateway frontend returns no ref due to `FROM scratch`:
```hlb
fs dockerfile() {
scratch
mkfile "/Dockerfile" 0o666 "FROM scratch"
}
fs default() {
frontend "docker/dockerfile:latest" with option {
input "context" scratch
input "dockerfile" dockerfile
}
}
```
```sh
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBuiltinChainStmt.func7.1.2.1(0x1dcd920, 0xc000454240, 0x1dcde20, 0xc0004ba100, 0x0, 0xc0004ba100, 0x27)
/Users/josh/Work/hlb/codegen/chain.go:347 +0x29d
```

Handle when frontend returns no ref

---

codegen/chain.go
codegen/codegen.go
codegen/output.go
codegen/sockproxy.go
module/resolve.go
solver/solve.go

- Fixes local import path for subdirectories to include subdirectory twice
- Removes unnecessary errgroup for solver.Build when it used to handle sessions

Fix deadlock with remote resolver when other errgroup routines fails

---

solver/progress.go

Previously, p.Write errors were handled by code to extract the grpc stacktrace from BuildKit. It was logged to console, but returned nil error, which causes HLB to return exit code 0.

Return error from p.Write back to the wait group

---

builtin/builtin.go
checker/builtin.go
checker/checker.go
checker/errors.go
codegen/chain.go
codegen/codegen.go
codegen/debug.go
codegen/decl.go
gen/builtins.go
gen/documentation.go
langserver/server.go
parser/cst.go
parser/unparse.go
report/report.go
report/syntax.go

Differentiating `ObjType` and `Type` is confusing, and we typically named `ObjType` and `Type` variables both as `typ` because `type` is a keyword in golang. Using `Kind` keeps this simple.

Refactor ObjType and typ to Kind and kind

---

codegen/chain.go
codegen/output.go

This PR changes `frontend` to modify the current `llb.State` with the returned image spec. 
For example, running this hlb file:
```
fs dockerfile() {
scratch
mkfile "/Dockerfile" 0o666 string {
template <<-EOF
FROM alpine:latest
LABEL dockerfile-label="value"
ENV foo=bar
EOF
}
}
fs build() {
label "early-label" "some value"
frontend "docker/dockerfile" with option {
input "context" fs { scratch; }
input "dockerfile" dockerfile
}
label "late-label" "some other value"
}
fs default() {
build
dockerLoad "my/image"
}
```
should produce a local image with the following metadata:
```
{
"Hostname": "",
"Domainname": "",
"User": "",
"AttachStdin": false,
"AttachStdout": false,
"AttachStderr": false,
"Tty": false,
"OpenStdin": false,
"StdinOnce": false,
"Env": [ …
```

use the image spec returned from the remote frontend

---

codegen/builtin_option.go

After refactoring to new `codegen`, the `secret` builtin was missing path resolution.

Fix secret missing path resolution

---

codegen/value.go

Reproducible only with a complex build with multiple `dockerPush`.

Deep copy fs value to avoid sharing slices of options

---

codegen/builtin_fs.go
codegen/builtin_option.go
pkg/imageutil/buffered_resolver.go

- Resolve is now no-op as planned. Deprecation for `resolve` should show up in `linter` from: https://github.com/openllb/hlb/pull/181
- Entire image config kept from resolve config into new `codegen.Filesystem`, since `llb.WithMetaResolver` throws away a lot of the config.

Fix regression for image config not persisted from image resolve

---

cmd/hlb/command/lint.go
codegen/codegen_test.go
hlb.go
langserver/server.go
linter/linter.go
module/resolve.go

- Relpaths for imports importing modules from its directory does not properly construct path from hlb process's cwd
```hlb
import module from "./root/module.hlb"
fs default() {
module.foo
}
```
```hlb
import transient from "./transient.hlb"
export foo
fs foo() {
transient.bar
}
```
```hlb
export bar
fs bar() {
image "alpine"
}
```

Fix relative path resolution for imports

---

parser/cst.go
unparse_test.go

Source:
```hlb
fs default() {
run <<~repro
$k
repro
}
```
Before:
```
❯ hlb format foo.hlb
foo.hlb:3:17: no lexer rules in state "Heredoc" matched input text "$k\n        repro..."
exit status 1
```
After:
```sh
❯ hlb format foo.hlb
fs default() {
run <<~repro
$k
repro
}
```

Fix heredoc string interpolation

---

codegen/codegen.go
codegen/codegen_test.go

Leading and trailing whitespace is preserved when using `<<~` heredoc folds when it shouldn't. This causes issues when a path is specified as a heredoc and then `os.Stat` fails because there's a trailing space.
Confirmed test fails on master:
```sh
❯ go test -v -run TestCodeGen/heredoc_folding ./codegen
=== RUN   TestCodeGen
=== PAUSE TestCodeGen
=== CONT  TestCodeGen
=== RUN   TestCodeGen/heredoc_folding
--- FAIL: TestCodeGen (0.00s)
--- FAIL: TestCodeGen/heredoc_folding (0.00s)
codegen_test.go:866: expected: .
└── [file]  actions:<input:-1 secondaryInput:-1 mkfile:<path:"/foo" mode:420 data:"Hello world" timestamp:-1 > >
└── solve options
codegen_test.go:871: actual: .
└── [file]  actions:<input:-1 secondaryInput:-1 mkfile:<path:"/foo" mode:420 data:"Hello world " timestamp:-1 > >
└── …
```

Trim space when codegening heredoc folds

---

parser/cst.go
parser/unparse.go
parser/walk.go
unparse_test.go

Fixes: #195
Now that we have `UnparseOption`, we can do away with the special heredoc marker as well.

Fix heredoc and blockstmt indentation on unparse

---

mkdocs.hlb

Npm strikes again.
```
> /bin/sh -c 'npm install':
#26 1.224 npm notice
#26 1.224 npm noticenpm notice
#26 1.224 npm notice New patch version of npm available! 7.0.3 -> 7.0.5
#26 1.224 npm notice New patch version of npm available! 7.0.3 -> 7.0.5
#26 1.224 npm Changelog: <https://github.com/npm/cli/releases/tag/v7.0.5>
#26 1.224 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.0.5>
#26 1.224 npm notice Run `npm install -g npm@7.0.5` to update!
#26 1.224 npm notice notice Run `npm install -g npm@7.0.5` to update!
#26 1.224 npm notice
#26 1.224
#26 1.224 npm ERR! code EROFS
#26 1.224 npm ERR! code EROFS
#26 1.224 npmnpm ERR! syscall open
#26 1.225 npm ERR! path /src/package-lock.json
#26 1.224  ERR! syscall open
#26 1.224 npm ERR! path /src/package-lock.json
#26 1.225 npm …
```

Allow npm to modify lock but discard the results

---

codegen/codegen.go
codegen/codegen_test.go
langserver/server.go
parser/cst.go
parser/unparse.go

Allow for escaped fragments within heredocs to keep consistency with string fragments.
Example:
```hlb
fs default() {
mkfile "foo" 0o644 <<~EOM
Escape this \${PATH}
EOM
}
```

Add escape fragments to heredocs

---

mkdocs.hlb
parser/cst.go
parser/unparse.go
parser/walk.go
unparse_test.go

Previously, a patch changed block formatting from handling newlines to delegating multi-line formatting to the underlying stmt unparsing, since with opts can now be plumbed down via `(parser.Node).Unparse(opts ...parser.UnparseOption)` for metadata like indentation.
However, comment groups didn't appropriately handle tabulation, so this PR fixes that issue and re-introduces comment groups to `FieldStmt`.

Fix formatting for multi-line comments

---

checker/checker_test.go
codegen/codegen_test.go
parser/unparse_test.go

Fixes indentation in `checker/checker_test.go` and use `dedent.Dedent` instead of the `cleanup` functions.

Cleanup tests and use dedent.Dedent for test cases

---

cmd/hlb/command/format.go
cmd/hlb/command/lint.go
cmd/hlb/command/module.go
linter/linter_test.go
parser/walk.go

- `opts` is common variable name for with options, so refactoring `FormatOptions` -> `FormatInfo`, etc.
- Add `linter/linter_test.go`
- Refactor linter CLI command to allow for external consumption.

Add linter test and refactor cli command with LintInfo

---

build.hlb
builtin/builtin.go
builtin/lookup.go
checker/checker.go
checker/checker_test.go
cmd/hlb/command/lint.go
codegen/value.go
language/builtin.hlb
linter/linter.go
parser/cst.go

- The name `group` and `parallel` has been confusing to explain to newcomers. After the last few months of usage, it seems more intuitive to be called `pipeline` and `stage`.
- Introduces linter rules and auto fix for the deprecation.

Deprecate groups, introduce pipelines

---

checker/checker.go
linter/linter_test.go
module/resolve_test.go

The semantic pass was changed recently but didn't consider the deprecated import path so it failed to register transitive import idents that were using the deprecated syntax.
Added a test suite for the resolver which fails before fix and succeeds after.

Add resolver test and fix import deprecated

---

checker/checker.go
checker/checker_test.go
codegen/value.go

This will allow non-fs functions to be run as a pipeline (e.g. `string localRun` that has side effects).
```
pipeline default() {
stage localRun("echo msg > foo")
stage local("foo")
}
```
Another example, where a tarball is made locally before running a build that depends on the tarball made.
```
pipeline default() {
stage localRun("./make-tarball.sh")
stage buildDependingOnTarball
}
```

Allow pipelines to run any non-option functions

---

build.hlb
version.go

- Fix the silently broken version subcommand in a previous PR by not including the `.git` directory
- Bump version constant to `0.3`

Bump version constant to 0.3

---

cmd/hlb/command/run.go
codegen/builtin_fs.go
codegen/builtin_string.go
codegen/context.go
codegen/resolver.go

- Previously, we resolve for every `image` call, even if its a duplicate. Since resolve is slow, this may end up being the slowest part of the cached builds.

Cache image config resolves within a single hlb run

---

codegen/codegen.go
errdefs/errors.go
module/resolve.go

- `--target run` says "arguments required" because its trying to execute the
builtin run. we shouldn't allow them to be viable targets
- `no such file or directory` has a race condition where stratum-agent was used
to lookup common.hlb when its supposed to be looking in stratum-hlb-service
- `no such file or directory` doesn't show a good error because buildkit
upstream has a bug, but i have a workaround
Follow up: https://github.com/openllb/hlb/issues/217

Fix multiple issues with resolving imports

---

codegen/builtin_fs.go
codegen/builtin_option.go

Tested with:
```
fs default() {
mountCore
dockerLoad "cmdtest:latest"
}
fs core() {
scratch
cmd "/this/is/dumb"
}
fs _fromMount() {
image "busybox"
run "/bin/true" with option {
mount core "/mnt" as mountCore
}
}
```
Desired outcome is the `cmd` from `core` is preserved in the mounted fs

preserve resolved config when fs used as mount binding

---

module/resolve.go

fixes #223
when we previously used `filepath.Dir(mod.Pos.Filename)` as the root, it would end up prepending the dir name twice.

module path contains directory

---

docs/intro/quickstart.md

Fix docs quick start compile instructions to match README

---

errdefs/errors.go
module/resolve.go

When importing an fs without the file found like so:
```hlb
import nodejs from fs {
local "./nodejs.hlb"
}
```
This PR fixes the panic:
```sh
[+] Building 0.2s (1/1)                                                                                                                                                                              
=> [import nodejs] local://sha256:<redacted> (nodejs.hlb)                                                                                0.1s
=> => transferring sha256:<redacted>: 32B                                                                                                0.1s
strings: negative Repeat count
goroutine 1 [running]:
runtime/debug.Stack(0xc0006baef8, 0x2173e00, 0x26b0300)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
```
To show …

Underline func lit type for import errors

---

checker/builtin.go
codegen/codegen_test.go
diagnostic/span.go
parser/cst.go
parser/unparse.go

This fixes two problems:
1) `(*SpanError).Pretty` would panic if there were no spans for the
file. This seemed to be an oversight, because the length of `spans` was
checked just below.
2) `Module`'s implementation of `Unparse` was used for `BuiltinDecl`.
This meant that unrecognized builtin errors would end up printing the
whole builtin module instead of just the name of the builtin.

Unparse BuiltinDecl correctly

---

codegen/builtin_fs.go

Some external systems depends on history to exist for things like labels.
For context, the history comment from buildkit is `buildkit.dockerfile.v0`.
Example:
```
"history": [
{
"created": "2021-03-31T20:10:06.686359124Z",
"created_by": "/bin/sh -c #(nop) ADD file:7119167b56ff1228b2fb639c768955ce9db7a999cd947179240b216dfa5ccbb9 in / "
},
{
"created": "2021-03-31T20:10:06.934368604Z",
"created_by": "/bin/sh -c #(nop)  CMD [\"/bin/sh\"]",
"empty_layer": true
},
{
"created": "2021-03-31T20:10:06.934368604Z",
"created_by": "LABEL image-name=foo",
"comment": "hlb.v0",
"empty_layer": true
},
{
"created": "2021-03-31T20:10:06.934368604Z",
"created_by": "RUN /bin/sh -c sleep 1",
"comment": "hlb.v0",
"empty_layer": true
},
{
"created": "2021-03-31T20:10:06.934368604Z",
"created_by": "LABEL …
```

Commit history matching Buildkit's Dockerfile2LLB logic

---

codegen/builtin_fs.go
codegen/builtin_option.go
codegen/value.go
solver/solve.go

Some systems depend on the `container_config` from v1 docker manifests (not present in official OCI image specs). Adding a compat layer during `dockerPush` evaluation.
Specifically, it's distributions manifest payload when requesting with `application/vnd.docker.distribution.manifest.v1+json`, activating this code:
https://github.com/distribution/distribution/blob/6affafd1f030087d88f88841bf66a8abe2bf4d24/manifest/schema1/config_builder.go#L183-L190
Modifying last history v1 compatibility with payload from the raw manifest config. This PR allows `container_config` to be plumbed into registry's automatic v1 translation to history with v1 compat.

Add v1 compatibility container-config

---

pkg/imageutil/buffered_resolver.go

it seems the `manifest` routine was fetching all the image blogs including the data blobs.  This PR filters out any blob with `rootfs` in the type, so it will fetch just the image metadata.  It seems to fix my issue with the function hanging.

skip fetching rootfs blobs for `manifest`

---

codegen/builtin_fs.go

- Currently newlines from multi-line runs like heredoc are eliminated from the custom name returned back in the progress UI.
- Multi-line progress line items don't render well, but having the literal symbol `\n` looks better and doesn't remove information.

Show newline symbols in llb.Run custom name

---

codegen/builtin_fs.go

This allows the digest of a pushed build to be consistent between runs
as long as the layer contents and other metadata remains the same.

Set an empty "created" timestamp when adding a layer, for build reproducibility

---

pkg/llbutil/secret.go
pkg/llbutil/secret_test.go

It seems we have lost the ability to use doublestar syntax when
matching secrets for inclusion/exclusion.  Not sure which refactoring
effort lost this, but replacing filepath.Walk with fsutil.Walk seems
to work.  Also adding in some tests to ensure we dont lose this
functionality again.

restore doublestar syntax for secret include/excludePatterns

---

cmd/hlb/command/module.go
cmd/hlb/command/run.go
codegen/builtin_fs.go
codegen/context.go
codegen/resolver.go
hlb.go
module/resolve.go
solver/multiwriter.go
solver/progress.go
solver/request.go

When a parallel solve involves overlapping vertices, HLB may print log
lines multiple times.
This works around the issue by adding our own `MultiWriter` implementation
which keeps track of which `Writer` returned by `WithPrefix` is responsible
for outputting logs for any particular vertex. Writes for the same
vertex will only be allowed through once.
Repro case:
fs default() {
output "hi"
download "."
}
fs common(string msg) {
image "docker-hub.netflix.net/library/busybox"
run "for i in $(seq 1 10); do echo $i; sleep 1; done" with ignoreCache
run "echo ${msg} > /output/${msg}" with option {
mount scratch "/output" as output
}
}

Avoid duplicated log output from parallel solves

---

codegen/debug.go

Without this check, `FindStaticBreakpoints` will wrongly see
option::run breakpointOpt() {
breakpoint "/overlay-chroot" "/bin/sh"
}
as a standalone breakpoint

Avoid false positive static breakpoint

---

cmd/hlb/command/module.go
cmd/hlb/command/run.go
codegen/context.go
codegen/debug.go
go.mod
solver/progress.go

This will now show the "plain" progress while debugging.  The goal is to ensure all progress output is flushed at various points, this is essential while in the debugger especially before we exec into a container.   There is no way to sync the progress writers we use upstream, but we can wait for completion, so this PR creates a `Sync` func in our progress writer which basically shuts down the current progress writer and waits for completion, then recreates the progress writer so that we can continue to collect progress later.

Add `Sync` to Progress to synchronize progress while debugging

---

cmd/hlb/command/run.go

found this with goleak testing

fix missing progress wait on exit from debugger

---

cmd/hlb/command/run.go
codegen/builtin_fs.go
codegen/builtin_string.go
codegen/codegen.go

It turns out some `Solve`s are invoked during the compile process, and
these were missing those options.

Pass WithEvaluate and WithErrorHandler to other solves as well

---

go.mod
go.sum
langserver/server.go

In preparation for committing to a stable v1 release for jrpc2 package, I have
made a number of updates to the library to simplify the API a bit. These
changes are discussed in creachadair/jrpc2#46 if you would like to offer input.
This commit updates the package version used here to the latest tag as of this
writing, v0.19.0, and updates the existing use to match the changes. These
changes should not produce any functional differences.

Update github.com/creachadair/jrpc2 to v0.19.0.

---

pkg/filebuffer/filebuffer.go

when running test with -race it seems there were multiple
check-then-write operations in parallel for the FileBuffer which
causes a `DATA RACE` exception

fix race to set sourcemap in FileBuffer

---

go.mod
go.sum

A follow-up to #263. No usage changes were required.

Update jrpc2 to v0.21.0.

---

codegen/builtin_fs.go
codegen/builtin_option.go
codegen/context.go
codegen/debug.go
codegen/value.go
module/resolve.go

This fixes the platform that is auto-magically swapping to the "default platform" when capturing fs's from mounts.   We now preserve the requested platform from the image and plumb it through were necessary.
Also `--debug` will now have the correct platform from the fs's image.

capture platform for fs's so we can ensure correct execution context

---

codegen/builtin_fs.go
codegen/codegen.go
codegen/value.go
langserver/server.go
linter/linter.go
module/resolve.go

As per usual, I was wrong: https://github.com/openllb/hlb/pull/275#discussion_r764482749
The empty Platform for the `zeroValue`  Filesystem is  used when we are operating directly on scratch, something like this:
```
fs default() {
copy build "/output" "."
download "."
}
fs build() {
image "alpine"
mkdir "/output" 0o755
run "touch /output/i-was-here"
}
```
We need to default the `zeroValue` platform to a valid value, otherwise we will get a `no match for platform in manifest: not found` error.

fix zero-value fs platform

---

codegen/builtin_fs.go
codegen/codegen_test.go
pkg/llbutil/id.go
pkg/llbutil/session.go
solver/request.go

- Removes `solver.LocalPathDescriptionKey`, it was used only to see what local's digest actually pointed to in the solver tree. Since the path is now part of the local name, this isn't necessary anymore. (https://github.com/openllb/hlb/pull/97#issuecomment-614268142)
- Use `localPath` as name for `llb.Local`, but under the hood use abs path for sync dir
- Use our deterministic ID in `llb.SharedKeyHint` instead, not visible to end user but gives us the same benefits
- Include filename in `localPath` when specifying a file directory with `local "filename"`. Doesn't have any functional difference but makes the output better
Before
```
~/tmp
❯ cat foo.hlb
fs default() {
local "foo.hlb"
}
~/tmp
❯ hlb run foo.hlb
[+] Building 0.0s (1/1) FINISHED
=> …
```

Refactor usage of llb.Local name and key hint

---

builtin/builtin.go
checker/builtin.go
checker/checker.go
checker/checker_test.go
client.go
cmd/hlb/command/context.go
cmd/hlb/command/langserver.go
cmd/hlb/command/lint.go
cmd/hlb/command/module.go
cmd/hlb/command/run.go
codegen/builtin.go
codegen/codegen.go
codegen/codegen_test.go
codegen/resolver.go
errdefs/errors.go
hlb.go
langserver/server.go
linter/linter.go
linter/linter_test.go
module/resolve.go
module/resolve_test.go
module/tree.go
module/vendor.go
parser/cst.go
parser/parse.go
parser/scope.go

- Previously, all `ImportDecl` in the AST are crawled and resolved before codegen even begins, even if they are not been used, and also disallows imports in imports since it was a one-pass.
- Imports are now emitted dynamically during codegen, making them (1) lazy, (2) recursive, allowing you to use imports within imports.
- Example, running `hlb run -t lint` no longer pulls in `image("openllb/go.hlb")` because its code path doesn't depend on the import even if the module does.
- Imports are evaluated before call{stmt,expr} arguments are evaluated because we need the type information for its arguments. The signatures are now embedded in the `(parser.Call{Stmt,Expr}).Signature` during `checker` for easy access.
- Codegen no longer needs to guess the arg types for `(*CodeGen).Evaluate` …

Refactor import modules into codegen using lazy async

---

codegen/value.go

No need to create goroutines and channels unnecessarily

Fast path register set when no async has been queued up

---

cmd/hlb/command/module.go
cmd/hlb/command/run.go
solver/progress.go
solver/progress_test.go

Currently the `solver.Progress` api requires calling `p.Release` and then `p.Wait`. This is the same everywhere and we might as well just consolidate it as `p.Wait`.

Remove unnecessary Release method from solver.Progress

---

checker/checker_test.go
codegen/codegen_test.go
langserver/server.go
linter/linter_test.go
module/resolve_test.go
parser/ast/match.go
parser/ast/match_test.go
parser/ast/walk.go
parser/ast/walk_test.go

- Refactors `ast.Find` to `ast.Search`
- Introduces new `ast.Find` that finds by line + column rather than by `strings.Contains`
- Adds tests for `ast.Match`, `ast.Search`, `ast.Find`, and `ast.IsPositionWithinNode`

Refactor ast.Find to ast.Search, introduce new ast.Find and tests

---

cmd/hlb/command/run.go
codegen/debug.go
pkg/steer/input_steerer.go
pkg/steer/input_steerer_test.go

- Also relaxed requirement to `io.WriteCloser` but would cast to `*io.PipeWriter` and `CloseWithError` if available.

Refactor InputSteerer to pkg/steer and add tests

---

checker/checker.go
codegen/builtin_fs.go
codegen/codegen.go
codegen/value.go
langserver/server.go
parser/ast/ast.go

This makes codegen fully asynchronous, as arguments will also be evaluating asynchronously.
```hlb
fs default() {
image "alpine"
copy image("other") "/etc/os-release" "/a"
}
```
Previously in https://github.com/openllb/hlb/pull/289, `SetAsync` was introduced and each block literal was executed asynchronously by creating a chain of goroutines piping to each other. However in the example above, `image("other")` will only start resolving image config once `image "alpine"` was done because each line depended on the line above it.
In this PR, `image("other")` will be executed asynchronously, and `copy` will block until its arguments have resolved.
If a builtin `Callable` required an argument like `input Value` instead of `input Filesystem`, it is further delayed until the builtin decides to …

Evaluate arguments asynchronously and delay register to value un-lazying

---

codegen/codegen.go
codegen/codegen_test.go
codegen/context.go
module/resolve.go

Broken somewhat by #290
Even before that PR, relative paths in remote imports was still broken.
- `flightcontrol` cancels the context provided to its function callback once its executed, for remote imports we hold on to a gateway build to keep the refs for the import fs alive until codegen exits. This was switched to `singleflight` that doesn't have context cancellation.
What was broken is best illustrated by an example:
```hlb
import other from "./sub/other.hlb"
fs default() {
other.build
}
```
```hlb
import common from "../common.hlb"
export build
fs build() {
common.build
}
```
The content of `./common.hlb` doesn't matter.
When evaluating the line `import common from "../common.hlb"` we need to resolve `../common.hlb` relative to the `./sub` directory, this was fixed in this PR. …

Resolve import rel paths correctly in both local and remote imports

---

cmd/docgen/main.go
cmd/hlb/command/format.go
cmd/hlb/command/lint.go
cmd/hlb/command/module.go
cmd/hlb/command/run.go
codegen/debug/tui.go
hlb.go
module/resolve.go
parser/directory.go
parser/parse.go
solver/directory.go

- Bring consistency of `info.Stdin`, `info.Stderr` to other commands
- Bring consistency of module parsing to other commands
- Allow extension of module URIs
- Refactor `remoteDirectory` to `solver.NewRemoteDirectory`
```sh
❯ hlb run -
fs default() {
image "alpine"
}
#1 resolve image config for docker.io/library/alpine:latest
#1 DONE 0.4s
#2 docker-image://docker.io/library/alpine:latest
#2 CACHED
```
Use `Ctrl+D` to terminate stdin input.
```sh
❯ echo 'fs default() { image "alpine" }' | hlb run -
#1 resolve image config for docker.io/library/alpine:latest
#1 DONE 0.4s
#2 docker-image://docker.io/library/alpine:latest
#2 CACHED
```

Refactor to allow extension of module uris

---

cmd/hlb/command/lint.go
cmd/hlb/command/module.go
cmd/hlb/command/run.go
codegen/codegen.go
codegen/uri.go
errdefs/errors.go
module/resolve.go
parser/ast/ast.go
rpc/langserver/server.go

- `(*codegen.CodeGen).EmitImport` uses the same `ParseModuleURI`.
Example:
```hlb
import go from "git://github.com/openllb/hlb@master:/go.hlb"
fs default() {
go.lint src
}
fs src() {
local "." with includePatterns("**/*.go", "go.mod", "go.sum", ".golangci.yml", ".git", "**/*.json")
}
```

Support URIs in import decl

---

solver/solve.go

This could lead to a panic if the semaphore could not be acquired due to
the context being cancelled, but the `Release` below was still reached.

Fix missing semaphore error check

---

module/resolve_test.go
parser/ast/ast.go
parser/directory.go
solver/directory.go

The ast.Directory Close is never called, so that ends up holding
the Solves running for the entire build.  See:
https://github.com/openllb/hlb/pull/323#issuecomment-1190974238
For now removing Close from the interface until we can figure out how
to more narrowly scope the remote directory usage.  This also moves
the file lookups to be synchronous on use (so still lazy if never used).
This could have a large impact if we were to access many files from
the remote directory, but typically I think we use this to just
import the `module.hlb` file for a remote import.
Future optimizations might be to ref-count the solve so we can reuse
the single solve for the life time of all the files returned from
Directory.Open.

remove async solves for remote-directories

---

cmd/hlb/command/run.go
solver/solve.go

Came across the issue when testing the `shell-on-error` implementation.
If the debugger returns the [`ErrDebugExit`](https://github.com/openllb/hlb/blob/master/codegen/debugger.go#L378) error, the error string gets [wrapped](https://github.com/moby/buildkit/blob/master/client/solve.go#L242) in the main solve goroutine after the gRPC call. Error check on `ErrDebugExit` fails [afterwards](https://github.com/openllb/hlb/blob/master/cmd/hlb/command/run.go#L324) because we lose the original error from the gRPC call.
This PR overrides the solve error to the original error, so the error check on `ErrDebugExit` succeeds.

Override the solve error if ErrorHandler returns an error

---

codegen/debug/tui.go
codegen/debugger.go
codegen/gateway_exec.go

The `env []string` support was removed from `ExecWithSolveErr` in #286. Adding it back because it's required in newt.
This PR adds `env []string` to the client-facing `Exec` method, instead of the underlying implementation (`ExecWithSolveErr` or `ExecWithFS`).

Support extra env vars for the debug shell

---

codegen/debugger.go

This PR fixes an issue where the debugger would hang at [`d.mode = <-d.control`](https://github.com/openllb/hlb/blob/master/codegen/debugger.go#L369) if `d.mode` is already `DebugTerminate`, and there is no more `control` value from the channel.

Exit early on ErrDebugExit after Solve

---

cmd/hlb/command/run.go
solver/multiwriter.go
solver/progress.go

This PR adds a platform prefix to Buildkit progress output, because the output is confusing when Newt solves multi-platform builds in parallel. However, the current implementation doesn't cover all output in plain mode. Buildkit doesn't give us a way to inject prefixes to the rest of the progress output:
- https://github.com/moby/buildkit/blob/master/util/progress/progressui/printer.go#L131
- https://github.com/moby/buildkit/blob/master/util/progress/progressui/printer.go#L198
Progress output with the current implementation:
Let me know what you think, or if you have any suggestions.

Add platform prefix to MultiWriter

---

cmd/hlb/command/run.go
parser/parse.go

Previously, this was being set to ".", and would wrongly strip the first
"." from a path that begins with "." in `ModuleDir`. Setting it to the
empty string seems more correct: nothing will be stripped. The only
other use of this "root" is in `filepath.Join` calls inside `localDirectory`
methods, which will also do the right thing with an empty string.
Fixes #332

Set implicit local directory path to ""

---

codegen/builtin_fs.go
codegen/codegen_test.go
codegen/context.go
hlb.go
pkg/llbutil/session.go

This ends up referring to an ID that isn't used by the actual session, so it causes problems. For example, "local" ops take at least 5 seconds because they try to wait for a session with this ID that never shows up: https://github.com/moby/buildkit/blob/abde08a5531d809a395cf648a31bca932b009af0/source/local/local.go#L95-L101
Ideally, we should set `SessionID` to the actual session ID instead of leaving it unspecified, because this relies on buildkit to iterate over the sessions and find one that works, which can be nondeterministic. But it seems like this would take a pretty significant refactor to create the session in advance, and then add `FSSyncProvider`s as we go. The change here should be a strict improvement over the current behavior.

Remove SessionID from local op

---

codegen/builtin_fs.go
pkg/imageutil/buffered_resolver.go

Previously, HLB never provided credentials to image resolvers, so image resolution wouldn't work against registries that require authentication. This shims standard buildkit authprovider to provide credentials based on the local Docker configuration, so we reuse that logic instead of copy/pasting it.

Provide registry creds to image resolver

---

pkg/llbutil/id.go

I ran into a situation where a "local" mount was wrongly deduped with a "local" from a concurrent solve that was created by another hlb process before some files in that dir were modified.
By including the last modified timestamp in the unique ID, we an avoid this deduplication in the case where a file has actually changed.

Include last modified time in LocalUniqueID

---

codegen/builtin_fs.go

Without this, it seems run commands run as root even if they are run against an image that specifies a `USER`.

Default user for run builtin to value from fs

---

codegen/builtin_option.go

We dont care about mutations to mounts unless they are bound with `as name` syntax.  However, buildkit does not know this so it assumes that mounts are mutable and will may be used elsewhere, so anytime we use a mount (including `local`) it will prevent buildkit from caching the vertex.

use ForceNoOutput for mounts that are not bound

---

codegen/builtin_fs.go
codegen/builtin_option.go
codegen/codegen.go
codegen/codegen_test.go
codegen/context.go

For some reason llb.ForceNoOutput is not matching [llb.MountOption in the switch statement](https://github.com/openllb/hlb/blob/1e65e28f9153988049f3c36ea9007067ccda8d92/pkg/llbutil/llbutil.go#L70) that applies options to mounts, so just forcing the type.
After more more debuggging it seems the llb.ForceNoOutput is useful for the cases where we mount sources from external locations (http, git), this allows cached results without forcing us to awkwardly use `with readonly`.
Our current builds currently do something like:
```
fs _build() {
image mybase
run "go build" with option {
mount local(".") "/src" as build
}
}
```
The usage of `local` seems to invalidate the cache, even if the contents are the same, and note we can't apply ForceNoOutput because we bind the mount.   I started a [slack …

fix llb.MountOption cast

---

codegen/builtin_fs.go

More defaulting is required to fix same issues as #354 where os/arch is required by buildkit

default os/arch for image export

---

codegen/builtin_fs.go

More defaulting is required to fix same issues as #354 where os/arch is required by buildkit

default os/arch for image export via docker load
