openllb/hlb

- codegen/codegen.go
Currently when reusing a locals definition I will see something like:
```
=> local://5ynzg3qmv2r4js718y3gkrorc                     0.1s
=> => transferring 5ynzg3qmv2r4js718y3gkrorc: 23.55kB    0.1s
=> local://63vy01nkeziqyd4sxvont84r1                     0.2s
=> => transferring 63vy01nkeziqyd4sxvont84r1: 23.55kB    0.1s
```
With this patch it will consistently hash based on path and local options:
```
=> local://bcb9151403a8f8668bd002cd4dcae9126ba9ae7910ce0465a66998fda3254ce3                0.1s
=> => transferring bcb9151403a8f8668bd002cd4dcae9126ba9ae7910ce0465a66998fda3254ce3: 514B  0.1s
```
> ensure locals have consistent hashes to prevent redundent data transport

- codegen/codegen.go
- report/errors.go
> Bubble up LLB validation errors with file position during codegen

- cmd/hlb/command/run.go
fixes #12.  If LogOutput is unset or set to `auto` we will detect if the Output is a tty and choose between `plain` and `tty` for the LogOutput setting.
> [#12] add support for `auto` log-output option

- checker/checker.go
This is likely better addressed when we add the ability to create fs methods, but for now this will bail on invalid statements when processing filesystems.
So given:
```
fs default() {
scratch
nothing fs { scratch; }
}
fs nothing(fs repo) {
scratch
}
```
We will now see:
```
./hlb --addr docker-container://buildkitd run --log-output plain ./tests/bug.hlb
#1 compiling ./tests/bug.hlb
#1 ERROR: ./tests/bug.hlb:3:3: unexpected filesystem statement: "nothing"
------
> compiling ./tests/bug.hlb:
------
```
I did file #26 since the error message is now shown when with tty output.
> [#9] prevent panic on unexpected filesystem statement

- hlb.go
- module/resolve.go
- module/tree.go
- module/vendor.go
> Fix running HLB from stdin using relative imports

- .github/workflows/test.yml
- checker/checker.go
- compile_test.go
- parse_test.go
Fixes issue introduced in #27
Add basic compile/checker tests for some issues we have seen.
Modify github workflow to run go test
> add compile tests, run go tests with github workflows

- builtin/builtin.go
- gen/builtins.go
- gen/documentation.go
- hlb.go
- language/builtin.hlb
- parser/cst.go
- parser/unparse.go
- parser/walk.go
Updates builtin.hlb for changes made in #54 and #56
> update builtin specs for recent changes

- checker/checker.go
- codegen/decl.go
- codegen/expr.go
- compile_test.go
> [#80] fix variadic options as argument

- cmd/hlb/command/run.go
```sh
$ hlb run --tree source.hlb
[+] Building 1.0s (1/1) FINISHED
=> compiling [default]                                                                                                                                               1.0s
.
└── parallel
└── parallel
├── single
│   └── [exec]  meta:<args:"/bin/sh" args:"-c" args:"v=$(git describe --match 'v[0-9]*' --tags --dirty='.dirty' --always | sed 's/^v//') && LDFLAGS=\"-X github.com/openllb/hlb.Version=$v\" /cross/build \"github.com/openllb/hlb/cmd/hlb\"" env:"PATH=/osxcross/target/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" env:"GOLANG_VERSION=1.13.10" env:"OSX_CROSS_PATH=/osxcross" env:"GOPATH=/root/go" env:"GO111MODULE=on" cwd:"/go/src/hlb" > mounts:<dest:"/" > mounts:<input:1 …
```
> Add --tree to hlb run in order to dry-run and print solve tree

- checker/checker_test.go
Simplifies the test to be specific for the `checker` package.
> Move compile_test.go to checker_test.go

- .gitignore
- checker/checker_test.go
> Test scope and identifiers

- checker/checker.go
- checker/checker_test.go
- checker/errors.go
- Currently it panics, so this adds the appropriate checker error and tests.
> Emit error when calling module without selector

- checker/checker.go
- checker/checker_test.go
- Fails with the new test without the fix, passes with the fix.
> Fix calling selector with arg from function field

- codegen/codegen_test.go
> Test codegen basic cases

- .github/workflows/test.yml
- docs/reference.md
- docs/templates/reference/reference.md
- mkdocs.hlb
- scripts/mkBuildkitdDroplet.sh
Also adding a step to PR build to verify generated files are up-to-date
> fix template for reference.md

- go.mod
- go.sum
> update hlb to use doublestar fork for fsutil

- checker/checker.go
- checker/checker_test.go
> Fix checker error for using non-zero arg builtins as args

- go.mod
- go.sum
Bump participle to `5b536bedbb9d75f77e68ddc0787569131b779fe4`
> Unfork participle and bump to master

- codegen/chain.go
- codegen/codegen_test.go
> Fix imported withopts

- codegen/builtin_fs.go
```
fatal error: concurrent map writes
goroutine 181 [running]:
runtime.throw(0x23051fb, 0x15)
/usr/local/go/src/runtime/panic.go:1112 +0x72 fp=0xc0005e4910 sp=0xc0005e48e0 pc=0x1035da2
runtime.mapassign_faststr(0x20d26e0, 0xc0003431d0, 0x22fccf8, 0x10, 0xc000452309)
/usr/local/go/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc0005e4978 sp=0xc0005e4910 pc=0x1015357
github.com/moby/buildkit/client/llb.addCap(...)
/go/src/stash.corp.netflix.com/engtools/newt/vendor/github.com/moby/buildkit/client/llb/source.go:468
github.com/moby/buildkit/client/llb.(*ExecOp).Marshal(0xc0007a5080, 0x2597cc0, 0xc00019e008, 0xc000364540, 0xc00033f650, 0xc0005e58f0, 0xc0005e5948, 0xc0005e5918, 0xc000364540, 0xc00033f650, ...)
/go/src/stash.corp.netflix.com/engtools/newt/vendor/github.com/moby/buildkit/client/llb/e …
```
> Avoid concurrent map write by casting to request outside of goroutine

- module/resolve.go
Fixes an issue with locals (and anything else that depends on sessions) in `fs` imports.
```
import module from fs {
local "./root"
}
fs default() {
module.version
}
```
```
export version
fs version() {
scratch
}
```
> Run a session for remote import resolves

- build.hlb
- go.hlb
- go.mod
- go.sum
- mkdocs.hlb
- parse.go
- parser/parse.go
- report/helper.go
- report/lexer.go
- Fixes EndPos including ellided tokens
- Performance improvements
- EBNF output
- Experimental codegen included but not enabled for HLB yet
> Bump to participle v1 branch

- checker/checker.go
- checker/checker_test.go
- codegen/codegen.go
- errdefs/errors.go
- langserver/server.go
- module/resolve.go
- parser/cst.go
> Fix remote modules importing local paths and improve no bind closure error

- cmd/hlb/command/module.go
- Previously split `checker.Check` to `checker.SemanticPass` and `checker.Check`, but did not update `hlb mod ...` commands
- Add new diagnostics handling for `hlb mod ...` commands
> Fix hlb mod sub-commands, missing semantic pass and error handling

- cmd/hlb/command/run.go
- go.mod
- solver/progress.go
> Remove direct dependency on containerd/console

- codegen/builtin_fs.go
- Missed as part of a refactor sometime ago
> Frontend errgroup was not waited as a solve option

- solver/progress.go
I noticed the progress output was sometimes getting truncated.  Turns out to be a regression from #246 with the MultiWriter migration.   This patch correctly signals the progress printer we are done and waits for all the data to be flushed.
> ensure progress is flushed when released

- cmd/hlb/command/run.go
- codegen/debug.go
- solver/request.go
- solver/solve.go
When the debugger is enabled, exec an interactive shell to troubleshoot
a solve error.
> Exec an interactive shell on error when in debug mode

- cmd/hlb/command/run.go
This is needed to avoid a goroutine leak in the shell-on-error case.
> Add missing pipe close

- codegen/builtin_option.go
- pkg/sockproxy/run.go
Without this we can only handle one incoming connection on the UDS.
Subsequent requests try to reuse the previous connection and typically
hang.
cc @slushie @aaronlehmann This should fix the issue as per the discussion today.
> reconnect to forwarded tcp for each request

- codegen/context.go
Turns out there aren't a lot of darwin/amd64 docker images 🤦
> use linux as default platform

- codegen/codegen.go
> Fix nil register dereference

- cmd/hlb/command/module.go
- cmd/hlb/command/run.go
- module/tree.go
Was broken by the progress refactor
> Fix broken hlb mod commands

- go.mod
- solver/progress.go
- solver/progress_test.go
- Add tests for progress
- Is there a better alternative to `os.Stderr` for the `solver.Console`?
> Add progress tests and remove unused Write function

- checker/checker.go
- codegen/codegen_test.go
- Broken from #290
- Added test to catch future regressions
> Check references on nested call expr

- parser/ast/context.go
- parser/parse.go
- Breaking up #286 into smaller PRs
> Add parsed modules to module lookup registry in context

- parser/ast/walk.go
- parser/ast/walk_test.go
- Simplifies and addresses some test issues
> Simplify ast.Find and fix tests

- codegen/builtin_fs.go
- codegen/codegen.go
- Also wrap non diagnostic error from builtin with diagnostic error
> Always use passed down val as starting point for fs

- build.hlb
- builtin/lookup.go
- codegen/builtin.go
- codegen/builtin_fs.go
- codegen/builtin_option.go
- docs/reference.md
- language/builtin.hlb
- pkg/stargzutil/fixtures/alpine.json
- pkg/stargzutil/fixtures/alpine_desc.json
- pkg/stargzutil/fixtures/alpine_index.json
- pkg/stargzutil/fixtures/alpine_index_desc.json
- pkg/stargzutil/fixtures/alpine_stargz.json
- pkg/stargzutil/fixtures/alpine_stargz_desc.json
- pkg/stargzutil/stargzutil.go
- pkg/stargzutil/stargzutil_test.go
- solver/solve.go
See: https://github.com/moby/buildkit/blob/master/docs/stargz-estargz.md
Example manifest:
```json
{
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"schemaVersion": 2,
"config": {
"mediaType": "application/vnd.oci.image.config.v1+json",
"digest": "sha256:cba6a63f22c24075f2f0c9efeea9603dc9845aa3afcec9cd061c08f5d12ecc75",
"size": 1031
},
"layers": [
{
"mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
"digest": "sha256:25af8f56fba7da444a7be3ff6a6df9ad9c15b19c624e1c2338bb0d1b1b226f69",
"size": 314668980
},
{
"mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
"digest": "sha256:7c084638d9c588cc1efc79c73a44e1424899eb10b4067119393a0dfab8400876",
"size": 485,
"annotations": {
"containerd.io/snapshot/stargz/toc.digest": …
```
> Add support for stargz images

- parser/parse.go
> Fix running hlb in relative parent/subdirectory

- pkg/steer/input_steerer_test.go
The assertion
require.Equal(t, "b", string(p2[:n]))
would not always succeed, because the InputSteerer may have read "b"
from the input before the test pushed the new writer.
Fix this by allowing the reads from the input to progress one byte at a
time, and blocking the read of the second byte until the new writer has
been pushed.
> Fix race in TestInputSteerer

- pkg/filebuffer/filebuffer.go
openllb/hlb#286 changed `FileBuffer` to return a newly constructed `SourceMap` on each call to the `SourceMap` method. This causes a dramatic increase in the gRPC request size, because It turns out that BuildKit deduplicates source maps based on pointer address: https://github.com/moby/buildkit/blob/d21254e7f74b49a84c3fbe1b13260cb23954cf92/client/llb/sourcemap.go#L57
Reuse the same `SourceMap` structure when nothing has changed.
> Return cached SourceMap in FileBuffer
